name: Testing Library Selectors Package

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm run test:coverage

  publish:
    needs: test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run generate:declaration
      - name: Publish if version has been updated
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        name: Create release if version has been updated
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: ${{ steps.publish.outputs.type }}
          release_name: "Release ${{ steps.publish.outputs.version }}"
          release_version: "Version ${{ steps.publish.outputs.version }}"